// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEujIg85IqEc5v-WGXTO87-E1C2lqfF7o',
    appId: '1:921119528673:web:3ae15b0fae64d698fc09a0',
    messagingSenderId: '921119528673',
    projectId: 'goodthings-53650',
    authDomain: 'goodthings-53650.firebaseapp.com',
    storageBucket: 'goodthings-53650.firebasestorage.app',
    measurementId: 'G-GSPSDVXVK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaIeNnJAykRW_1SAc58qt2es9tS_tClSM',
    appId: '1:921119528673:android:ab148cc686e0bc65fc09a0',
    messagingSenderId: '921119528673',
    projectId: 'goodthings-53650',
    storageBucket: 'goodthings-53650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAroX7SsuYsiXj4vgMJqqdKmM__coCR2p4',
    appId: '1:921119528673:ios:8039ae37dcb5a7e7fc09a0',
    messagingSenderId: '921119528673',
    projectId: 'goodthings-53650',
    storageBucket: 'goodthings-53650.firebasestorage.app',
    iosBundleId: 'com.example.goodthings',
  );
}
